//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khronos_PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ID { get; set; }
        public string Note { get; set; }
        public int WorkerID { get; set; }
        public int UnitID { get; set; }
        public int ProjectID { get; set; }
        public System.DateTime Date { get; set; }
        public int Manhour { get; set; }
        public decimal Expense { get; set; }
    
        public virtual WorksOn WorksOn { get; set; }
    }
}
