//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khronos_PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.Children = new HashSet<Unit>();
            this.Workers = new HashSet<WorksOn>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AncestorID { get; set; }
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public decimal Expense { get; set; }
        public System.DateTime DueDate { get; set; }
        public int Priority { get; set; }
        public int Status { get; set; }
        public double EstManhours { get; set; }
        public double SpentManhours { get; set; }
        public bool Active { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Children { get; set; }
        public virtual Unit Ancestor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksOn> Workers { get; set; }
    }
}
