//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khronos_PMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksOn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorksOn()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int WorkerID { get; set; }
        public int UnitID { get; set; }
        public int ProjectID { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual AssignedTo AssignedTo { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
