//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khronos_PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedTo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignedTo()
        {
            this.WorksOns = new HashSet<WorksOn>();
        }
    
        public int ProjectID { get; set; }
        public int WorkerID { get; set; }
        public bool Active { get; set; }
    
        public virtual Worker Worker { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksOn> WorksOns { get; set; }
    }
}
