//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khronos_PMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosureUnit
    {
        public int ID { get; set; }
        public int AncestorID { get; set; }
        public int Depth { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Unit AncestorUnit { get; set; }
    }
}
